package org.dynamiclayout.core.ui
enum class UIDataType {
    AMOUNT, BOOLEAN, COST1, COST2, CUSTOMIZED, DATE, DECIMAL,
    EMPLOYEE, GROUP, INT, KONTO, LOCALE, LONG, NUMBER,
    PASSWORD, PICTURE, STRING, TASK, TIME, TIMESTAMP, TIMEZONE, USER
}
